const API='https://zfviigipxxjvlrfrmmir.supabase.co';
const KEY='sb_publishable_IV9wSnMF7H6GUJNkfLtjRQ_vupmZcxJ';
const STUDIO='11111111-1111-4111-8111-111111111111';
let auth=null, mode='staff', state={person:null,role:null,branches:[],people:[],sessions:[],activities:[],memberships:[]};
const $=id=>document.getElementById(id);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function signIn(identifier,password){const body=mode==='staff'?{email:identifier,password}:{email:identifier,password};const r=await fetch(API+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});const t=await r.text();if(!r.ok)throw Error(t);return JSON.parse(t)}
async function api(path){const r=await fetch(API+'/rest/v1/'+path,{headers:{apikey:KEY,Authorization:'Bearer '+auth.access_token}});const t=await r.text();if(!r.ok)throw Error(t);return t?JSON.parse(t):[]}
function setMsg(t,good=false){$('loginMsg').textContent=t;$('loginMsg').className='msg '+(good?'success':'')}
function row(k,v){return '<div class="item"><span class="muted">'+esc(k)+'</span><strong>'+esc(v)+'</strong></div>'}
async function load(){const accounts=await api('user_accounts?select=studio_id,person_id,auth_user_id&auth_user_id=eq.'+auth.user.id);if(!accounts.length)throw Error('account');const account=accounts[0];const memberships=await api('studio_memberships?select=id,studio_id,person_id,role,status&person_id=eq.'+account.person_id+'&status=eq.active');const membership=memberships.find(m=>m.studio_id===STUDIO);if(!membership)throw Error('membership');state.role=membership.role;state.memberships=memberships;const [branches,people,sessions,activities,person]=await Promise.all([api('branches?select=id,name,studio_id&studio_id=eq.'+STUDIO+'&order=name'),api('people?select=id,studio_id,first_name,last_name,email,profile_status,lifecycle_status&studio_id=eq.'+STUDIO+'&order=created_at'),api('sessions?select=id,studio_id,branch_id,activity_id,instructor_person_id,starts_at,ends_at,capacity,status&studio_id=eq.'+STUDIO+'&order=starts_at'),api('activities?select=id,studio_id,discipline_id,name,description,duration_minutes,status&studio_id=eq.'+STUDIO+'&order=name'),api('people?select=id,first_name,last_name,email,profile_status,lifecycle_status&id=eq.'+account.person_id)]);state.branches=branches;state.people=people;state.sessions=sessions;state.activities=activities;state.person=person[0]||null;render()}
function render(){const role=state.role;const isStudent=role==='student';$('identity').textContent=(auth.user?.email||'')+' · '+role;$('chips').innerHTML=state.branches.map(b=>'<span class="chip">'+esc(b.name)+'</span>').join('')+'<span class="chip">'+esc(role)+'</span>';$('metrics').innerHTML='<div class="metric"><span class="muted">Sucursales</span><strong>'+state.branches.length+'</strong></div><div class="metric"><span class="muted">Personas</span><strong>'+state.people.length+'</strong></div><div class="metric"><span class="muted">Actividades</span><strong>'+state.activities.length+'</strong></div><div class="metric"><span class="muted">Sesiones</span><strong>'+state.sessions.length+'</strong></div>';$('sessionCount').textContent=state.sessions.length+' visibles';$('peopleCount').textContent=state.people.length+' visibles';$('sessionList').innerHTML=state.sessions.map(s=>{const a=state.activities.find(x=>x.id===s.activity_id);const b=state.branches.find(x=>x.id===s.branch_id);return '<div class="session"><strong>'+esc(a?.name||'Sesión')+'</strong><div class="detail">'+esc(new Date(s.starts_at).toLocaleString('es-MX',{dateStyle:'medium',timeStyle:'short'}))+' · '+esc(b?.name||'')+' · cupo '+s.capacity+'</div></div>'}).join('')||'<div class="empty">No hay sesiones visibles todavía.</div>';$('peoplePreview').innerHTML=state.people.slice(0,6).map(p=>'<div class="item"><div><strong>'+esc([p.first_name,p.last_name].filter(Boolean).join(' '))+'</strong><div class="detail">'+esc(p.email||'Sin correo')+'</div></div><span class="pill">'+esc(p.lifecycle_status)+'</span></div>').join('')||'<div class="empty">No hay personas visibles.</div>';$('peopleList').innerHTML=state.people.map(p=>'<div class="item"><div><strong>'+esc([p.first_name,p.last_name].filter(Boolean).join(' '))+'</strong><div class="detail">'+esc(p.email||'Sin correo')+' · '+esc(p.profile_status)+'</div></div><span class="pill">'+esc(p.lifecycle_status)+'</span></div>').join('')||'<div class="empty">No hay personas visibles.</div>';$('scheduleList').innerHTML=$('sessionList').innerHTML;$('profileRows').innerHTML=row('Auth UID',auth.user.id)+row('Rol',role)+row('Estudio','Demeter Fitness Studio')+row('Sucursal','QA Centro')+row('Modo','Sólo lectura en Bloque 1')+(isStudent?'<div class="warning">El login por celular todavía no se declara PASS. Esta cuenta QA fue provisionada inicialmente con correo y contraseña.</div>':'');$('peopleScope').textContent=isStudent?'Sólo deberías ver tu propia persona cuando el portal esté conectado.':'La lista está filtrada por RLS y la capability de tu membresía.'}
function show(view){document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));$(view).classList.remove('hidden');document.querySelectorAll('.nav button[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view))}
document.querySelectorAll('.nav button[data-view]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));
$('staffMode').onclick=()=>{mode='staff';$('staffMode').classList.add('active');$('studentMode').classList.remove('active');$('identifierLabel').textContent='Correo';$('identifier').type='email';$('identifier').placeholder='correo QA';$('loginHint').textContent='Acceso de equipo por correo y contraseña.'};
$('studentMode').onclick=()=>{mode='student';$('studentMode').classList.add('active');$('staffMode').classList.remove('active');$('identifierLabel').textContent='Correo QA temporal';$('identifier').type='email';$('identifier').placeholder='correo de prueba';$('loginHint').textContent='El adaptador celular + contraseña queda pendiente de cierre en Auth; esta cuenta QA usa correo temporal.'};
$('loginForm').onsubmit=async e=>{e.preventDefault();setMsg('Validando…');try{auth=await signIn($('identifier').value.trim(),$('password').value);await load();$('login').classList.add('hidden');$('app').classList.remove('hidden');setMsg('',true)}catch(err){setMsg('No se pudo acceder o no existe una membresía activa en el QA nuevo.')}};
$('logout').onclick=()=>location.reload();
